// Generated by cpp11: do not edit by hand
// clang-format off

#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// index.cpp
SEXP cpp_index_new(int dim, std::string path);
extern "C" SEXP _usearchlite_cpp_index_new(SEXP dim, SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_index_new(cpp11::as_cpp<cpp11::decay_t<int>>(dim), cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}
// index.cpp
void cpp_index_add(SEXP ptr, int id, cpp11::doubles vector);
extern "C" SEXP _usearchlite_cpp_index_add(SEXP ptr, SEXP id, SEXP vector) {
  BEGIN_CPP11
    cpp_index_add(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<int>>(id), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(vector));
    return R_NilValue;
  END_CPP11
}
// index.cpp
cpp11::writable::list cpp_index_search(SEXP ptr, SEXP query, int k);
extern "C" SEXP _usearchlite_cpp_index_search(SEXP ptr, SEXP query, SEXP k) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_index_search(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr), cpp11::as_cpp<cpp11::decay_t<SEXP>>(query), cpp11::as_cpp<cpp11::decay_t<int>>(k)));
  END_CPP11
}
// index.cpp
int cpp_index_size(SEXP ptr);
extern "C" SEXP _usearchlite_cpp_index_size(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_index_size(cpp11::as_cpp<cpp11::decay_t<SEXP>>(ptr)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_usearchlite_cpp_index_add",    (DL_FUNC) &_usearchlite_cpp_index_add,    3},
    {"_usearchlite_cpp_index_new",    (DL_FUNC) &_usearchlite_cpp_index_new,    2},
    {"_usearchlite_cpp_index_search", (DL_FUNC) &_usearchlite_cpp_index_search, 3},
    {"_usearchlite_cpp_index_size",   (DL_FUNC) &_usearchlite_cpp_index_size,   1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_usearchlite(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
